version: "1.0.{build}"
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
branches:
  only:
    - main
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore src/Journey.sln --verbosity q
build_script:
  - cmd: dotnet build src/Journey.sln -c Release
after_build:
  # For once the build has completed
  - cmd: dotnet pack src/Journey.sln -o packages -c Release
artifacts:
  - path: "packages/**/*.nupkg"
    name: NugetPackages

clone_depth: 1
test_script:
    - cmd: dotnet test src/Journey.sln
deploy:
  - provider: NuGet
    api_key:
      secure: 5RuQxlBbD68iriTG5fcWuZ52Qe8v3CuEGTBHJjH/hnfO4CWYoZe8KlVEf1EpMNq4

    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: main
