name: Generate and Publish NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    name: Generate and Publish NuGet Package
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/dotnet-interactive-learning/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Restore dependencies
      run: dotnet restore ./src
      
    - name: Build
      run: dotnet build --no-restore ./src
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release ./src/Extension
      
    - name: Publish NuGet package to GitHub Package Registry
      run: dotnet nuget push .\src\Extension\bin\Release\*.nupkg
      
