name: Generate and Publish NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    name: Generate and Publish NuGet Package
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release ./src/Extension
    - name: Publish NuGet package to GitHub Package Registry
      run: dotnet nuget push .\src\Extension\bin\Release\*.nupkg -k ${GITHUB_TOKEN} -s "https://nuget.pkg.github.com/dotnet-interactive-learning/index.json"
